Repository warleyvods-meli/meli-frescos, pull requests merged in 2021-07, with the labels that each got.

#13 Criação da entidade de produto
  src/main/java/com/mercadolibre/dambetan01/enums/ProductEnum.java
  src/main/java/com/mercadolibre/dambetan01/model/Product.java
Labels: enhancement

#14 Criando entidade Warehouse.java
  src/main/java/com/mercadolibre/dambetan01/model/Warehouse.java
Labels: enhancement

#15 update entity products
  src/main/java/com/mercadolibre/dambetan01/model/Product.java
Labels: enhancement

#17 Add batch stock
  src/main/java/com/mercadolibre/dambetan01/model/BatchStock.java
  src/main/java/com/mercadolibre/dambetan01/model/Product.java
Labels: enhancement

#25 Adicionando dados para data.sql
  src/main/resources/data.sql
Labels: melhoria

#27 create documentation
  README.md
  docs/guide/CHANGELOG.md
  docs/guide/README.md
  docs/guide/diagrams/db_diagram_v1.png
  docs/guide/index.html
Labels: documentation

#31 Adicionando e refatorando classes
  docker-compose.yml
  src/main/java/com/mercadolibre/dambetan01/controller/PurchaseOrderController.java
  src/main/java/com/mercadolibre/dambetan01/dtos/response/PurchaseOrderResponseDTO.java
  src/main/java/com/mercadolibre/dambetan01/enums/OrderStatus.java
  src/main/java/com/mercadolibre/dambetan01/model/Account.java
  src/main/java/com/mercadolibre/dambetan01/model/Buyer.java
  src/main/java/com/mercadolibre/dambetan01/model/CountryHouse.java
  src/main/java/com/mercadolibre/dambetan01/model/Product.java
  src/main/java/com/mercadolibre/dambetan01/model/PurchaseOrder.java
  src/main/java/com/mercadolibre/dambetan01/model/User.java
  src/main/java/com/mercadolibre/dambetan01/repository/AccountRepository.java
  src/main/java/com/mercadolibre/dambetan01/repository/PurchaseOrderRepository.java
  src/main/java/com/mercadolibre/dambetan01/service/IPurcharseOrderService.java
  src/main/java/com/mercadolibre/dambetan01/service/impl/PurchaseOrderServiceImpl.java
Labels: melhoria

#43 fix exception handler
  src/main/java/com/mercadolibre/dambetan01/config/ControllerExceptionHandler.java
  src/main/java/com/mercadolibre/dambetan01/controller/WareHouseController.java
  src/main/java/com/mercadolibre/dambetan01/exceptions/ApiError.java
  src/main/java/com/mercadolibre/dambetan01/exceptions/ApiException.java
  src/main/java/com/mercadolibre/dambetan01/exceptions/ApiExceptionControllerAdvice.java
  src/main/java/com/mercadolibre/dambetan01/exceptions/BadRequestException.java
  src/main/java/com/mercadolibre/dambetan01/exceptions/InternalServerErrorException.java
  src/main/java/com/mercadolibre/dambetan01/exceptions/NotFoundException.java
  src/main/java/com/mercadolibre/dambetan01/exceptions/ValidationError.java
  src/main/java/com/mercadolibre/dambetan01/exceptions/error/BadRequestException.java
  src/main/java/com/mercadolibre/dambetan01/exceptions/error/NotFoundException.java
  src/main/java/com/mercadolibre/dambetan01/exceptions/error/StandardError.java
  src/main/java/com/mercadolibre/dambetan01/exceptions/error/UnauthorizedException.java
  src/main/java/com/mercadolibre/dambetan01/exceptions/handler/ApiExceptionHandler.java
  src/main/java/com/mercadolibre/dambetan01/mapper/InboundOrderMapper.java
  src/main/java/com/mercadolibre/dambetan01/model/Authenticable.java
  src/main/java/com/mercadolibre/dambetan01/service/chain/InboundedOrder/CheckerByAgent.java
  src/main/java/com/mercadolibre/dambetan01/service/chain/InboundedOrder/CheckerByProductSection.java
  src/main/java/com/mercadolibre/dambetan01/service/chain/InboundedOrder/CheckerBySectionSpace.java
  src/main/java/com/mercadolibre/dambetan01/service/chain/InboundedOrder/CheckerByStockTemperature.java
  src/main/java/com/mercadolibre/dambetan01/service/chain/InboundedOrder/CheckerByWarehouse.java
  src/main/java/com/mercadolibre/dambetan01/service/chain/InboundedOrder/CheckerFinalyze.java
  src/main/java/com/mercadolibre/dambetan01/service/impl/AgentServiceImpl.java
  src/main/java/com/mercadolibre/dambetan01/service/impl/BuyerServiceImpl.java
  src/main/java/com/mercadolibre/dambetan01/service/impl/InboundOrderServiceImpl.java
  src/main/java/com/mercadolibre/dambetan01/service/impl/ProductServiceImpl.java
  src/main/java/com/mercadolibre/dambetan01/service/impl/PurchaseOrderServiceImpl.java
  src/main/java/com/mercadolibre/dambetan01/service/impl/SectionServiceImpl.java
  src/main/java/com/mercadolibre/dambetan01/service/impl/SessionServiceImpl.java
  src/main/java/com/mercadolibre/dambetan01/service/impl/StockServiceImpl.java
  src/main/java/com/mercadolibre/dambetan01/service/impl/WarehouseServiceImpl.java
Labels: bug

#44 DAY 2 - Full commit
  pom.xml
  src/main/java/com/mercadolibre/dambetan01/controller/PurchaseOrderController.java
  src/main/java/com/mercadolibre/dambetan01/dtos/ProductResponseDTO.java
  src/main/java/com/mercadolibre/dambetan01/dtos/request/PurchaseOrderRequestDTO.java
  src/main/java/com/mercadolibre/dambetan01/enums/OrderStatus.java
  src/main/java/com/mercadolibre/dambetan01/mapper/ProductMapper.java
  src/main/java/com/mercadolibre/dambetan01/mapper/PurchaseOrderMapper.java
  src/main/java/com/mercadolibre/dambetan01/model/Product.java
  src/main/java/com/mercadolibre/dambetan01/model/PurchaseOrder.java
  src/main/java/com/mercadolibre/dambetan01/repository/ProductRepository.java
  src/main/java/com/mercadolibre/dambetan01/repository/StockRepository.java
  src/main/java/com/mercadolibre/dambetan01/service/IProductService.java
  src/main/java/com/mercadolibre/dambetan01/service/IPurcharseOrderService.java
  src/main/java/com/mercadolibre/dambetan01/service/IStockService.java
  src/main/java/com/mercadolibre/dambetan01/service/impl/ProductServiceImpl.java
  src/main/java/com/mercadolibre/dambetan01/service/impl/PurchaseOrderServiceImpl.java
  src/main/java/com/mercadolibre/dambetan01/service/impl/StockServiceImpl.java
  src/main/resources/data.sql
Labels: melhoria

#49 add unit test for US001
  src/main/java/com/mercadolibre/dambetan01/config/WebSecurityConfig.java
  src/main/java/com/mercadolibre/dambetan01/model/Product.java
  src/main/java/com/mercadolibre/dambetan01/model/User.java
  src/main/java/com/mercadolibre/dambetan01/model/Warehouse.java
  src/test/java/com/mercadolibre/dambetan01/integration/WareHouseControllerTest.java
  src/test/java/com/mercadolibre/dambetan01/unit/ScopeUtilTest.java
  src/test/java/com/mercadolibre/dambetan01/unit/beans/RandomSampleBeanTest.java
  src/test/java/com/mercadolibre/dambetan01/unit/service/InboundOrderServiceImplTest.java
  src/test/java/com/mercadolibre/dambetan01/util/BuilderInboundOrderTestHelper.java
Labels: test

#63 Implementando JWT
  src/main/java/com/mercadolibre/dambetan01/Application.java
  src/main/java/com/mercadolibre/dambetan01/config/SpringDocConfig.java
  src/main/java/com/mercadolibre/dambetan01/config/WebSecurityConfig.java
  src/main/java/com/mercadolibre/dambetan01/controller/CountryHouseController.java
  src/main/java/com/mercadolibre/dambetan01/controller/PurchaseOrderController.java
  src/main/java/com/mercadolibre/dambetan01/controller/SessionController.java
  src/main/java/com/mercadolibre/dambetan01/dtos/response/AccountResponseDTO.java
  src/main/java/com/mercadolibre/dambetan01/model/Account.java
  src/main/java/com/mercadolibre/dambetan01/model/CountryHouse.java
  src/main/java/com/mercadolibre/dambetan01/repository/AccountRepository.java
  src/main/java/com/mercadolibre/dambetan01/security/CustomUserDetailService.java
  src/main/java/com/mercadolibre/dambetan01/security/JWTAuthenticationFilter.java
  src/main/java/com/mercadolibre/dambetan01/security/JWTAuthorizationFilter.java
  src/main/java/com/mercadolibre/dambetan01/security/SecurityConstants.java
  src/main/java/com/mercadolibre/dambetan01/service/AccountService.java
  src/main/java/com/mercadolibre/dambetan01/service/ISessionService.java
  src/main/java/com/mercadolibre/dambetan01/service/crud/ICountryHouseService.java
  src/main/java/com/mercadolibre/dambetan01/service/crud/impl/CountryHouseServiceImpl.java
  src/main/java/com/mercadolibre/dambetan01/service/impl/SessionServiceImpl.java
  src/main/resources/data.sql
Labels: melhoria

#66 Diagram class
  docs/guide/diagrams/class_diagram.png
Labels: documentation

#76 fix day 2 bug (#1)
  src/main/java/com/mercadolibre/dambetan01/controller/PurchaseOrderController.java
  src/main/java/com/mercadolibre/dambetan01/service/impl/PurchaseOrderServiceImpl.java
  src/main/resources/data.sql
Labels: bug, fix
